### ISSUE TITLE
Injection in Brave Search broken after page redesign

### ISSUE THREAD

**Issue by schossel** [Fivefold/linkding-injector#22] opened 2023-09-27 16:33 UTC
I can't get the extension to work anymore in Brave. It connects to linkding but doesn't inject any results into the Brave results. If I use google as search engine they are injected as intended.

**Comment by Fivefold** [comment] 2023-09-27 17:08
Thank you, I can reproduce the issue. Brave Search completely redesigned their search page and got rid of the sidebar that I used to put the results in. They switched to a mobile-first design with only a single column it seems.

There's two ways to solve this. I personally don't use Brave Search, so I would kindly ask you @schossel to tell me what you as a user would prefer.

@YMan84 you originally requested support for Brave Search, maybe you want to pitch in?
@Sevichecc I believe you use SearX but you at least worked on Brave Search as well. Maybe you have thoughts on this, too.

Anyway, here are the two options. Please keep in mind these are quick and dirty mockups, the actual boxes would conform closer to the page design:
**1. create my own sidebar** and put the injection box there. This will be the only sidebar content, since all regular content is in the main column:

![image](https://github.com/Fivefold/linkding-injector/assets/38764218/3f646c3a-6890-4fab-9b92-0eadda7f5ecc)


**2. put the injection box in the main column**, pushing down secondary results. For this option there would also be the question of _where_ to inject (right at the top, above News, below News)

![image](https://github.com/Fivefold/linkding-injector/assets/38764218/f1f49cc6-2c6f-4d19-8a03-57e1581df1ab)

**Comment by schossel** [comment] 2023-09-27 17:11
If it's not too much trouble I would prefer Nr 1.

**Comment by Fivefold** [comment] 2023-09-27 17:45
On further inspection Brave Search did indeed keep the sidebar. I will put it there then.

**Comment by schossel** [comment] 2023-09-27 18:06
If it works, I'm the last to complain.

**Comment by Fivefold** [comment] 2023-09-27 21:30
Should be fixed in v1.3.3. It's already available on firefox, the chrome web store will receive it probably within the next 24 hours. If the issue persists, please reopen this issue.

**Closed by Fivefold** 2023-09-27 21:30 UTC
Labels: bug, help wanted

**Comment by schossel** [comment] 2023-09-28 10:24
1.3.3 seems to work. Thanks!

**Comment by Sevichecc** [comment] 2023-10-31 13:49
Thanks for the fix!
