### ISSUE TITLE
Firefox extension connected, but no search results shown

### ISSUE THREAD

**Issue by gmiles32** [Fivefold/linkding-injector#15] opened 2023-05-26 21:50 UTC
I'm trying to get the firefox browser extension set up, and I'm having issues getting duckduckgo or google to show the linkding search results. My  extension is connected to my linkding instance, and I can see the the search requests going through in my linkding docker containers logs. However, no search results are presented in either duckduckgo or google. 

My firefox version is 113.0.1, and I've tried the same thing with Brave browser version 113.1.51.118. Any help of guidance on this issue would be much appreciate!

**Comment by Fivefold** [comment] 2023-05-27 19:52
Thank you for your report and trying to troubleshoot so far. 
duckduckgo seem to have changed their website code, so DDG support is currently broken. Hopefully I can push out a bugfix tomorrow.

It should work fine with google though, I can't reproduce your problem there. Are you searching for terms that actually deliver linkding results? (i.e. if you input the same query in your linkding instance it should return at least one result). If there are no results, the injection box won't show by design.

In case you _do_ expect results, please do the following:

1. On Firefox, go to any google search website (e.g. google.com)
2. Search for a term that actually delivers results on your linkding instance
3. Open the Web Developer Tools by pressing F12 and go to the 'Console' Tab. 
4. Look for any errors (shown in red) by `searchInjection.js` (look to the right side)
5. If you find one, right-click on the error, choose 'Copy message' and paste it here

If you're unsure, you can do the same at duckduckgo and will find the following error there (since DDG ist broken at the moment):
```Python
21:48:24.010 TypeError: d is null searchInjection.js:182:15
```

**Comment by gmiles32** [comment] 2023-05-27 20:15
Thank you for your help! I just tested the Google search results and it's working now - I think I just needed to step away from it for a bit.

**Comment by Fivefold** [comment] 2023-05-27 20:29
Glad it's working now! I will close this issue then. If you do experience problems again, feel free to reopen the issue.
Watch #16 to get notified when the fix is ready (in case you want to use DDG).

**Closed by Fivefold** 2023-05-27 20:29 UTC
