### ISSUE TITLE
Searching for tags

### ISSUE THREAD

**Issue by vaijns** [Fivefold/linkding-injector#24] opened 2024-01-13 18:27 UTC
Just started using linkding and found this extension and I think it's a pretty cool idea!
The only thing I'm missing is having bookmarks listed which don't have the keyword in the title or description but only in the tag I've added.

So e.g. I've created a bookmark on a site that has a cool button design or whatever and I've given it the tags "button" and "design". When I'm searching for something like "button design" on e.g. duckduckgo I'd like to see that bookmark.

Maybe it would even be nice to also see it if only some of these tags are in the keywords I've searched for. So even if I'm searching for "design idea button" I'd see that same bookmark which only has the tags "button" and "design" but is missing the tag "idea".
Might not always be what you want so maybe only do that if there isn't X (specified amount of bookmarks) matching results already.

**Comment by Fivefold** [comment] 2024-01-13 18:47
I think this might be a duplicate of #8 

This extension doesn't have it's own search logic, it just sends your query (whatever you put in the search box) to your linkding instance. In that way it works the same way as if you were to input that query into the linkding search box. Due to this I unfortunately can't easily alter the search logic and wouldn't want to do so.

If I understand you correctly, you _can_ already achieve the behaviour you want though. **Try turning on lax 'tag search' mode in the linkding settings (of your linkding instance).**

I will close this issue (because it's out of scope) but please report back if this works for you, in case someone else looks for this in the future.

**Closed by Fivefold** 2024-01-13 18:47 UTC

**Comment by vaijns** [comment] 2024-01-14 00:28
Oh, didn't know that's how it's implemented but makes sense to not do it then.
turning on lax tag search actually helps (shows those bookmarks I didn't see before).
Thanks a lot! :)
